name: Tests
on: push
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen
      run: docker build --tag islasgeci/validate_tdp:latest --tag islasgeci/validate_tdp:${GITHUB_SHA:0:4} .
    - name: Verifica el formato
      run: docker run islasgeci/validate_tdp:latest make check
    - name: Corre pruebas y evalúa cobertura
      run: docker run islasgeci/validate_tdp:latest make coverage
    - name: Create/Update tag
      uses: rickstaa/action-create-tag@v1.5.4
      with:
        tag: "latest"
        message: "Latest release"
        force_push_tag: true
    - name: Docker log-in
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
    - name: Sube latest a Docker Hub
      run: docker push islasgeci/validate_tdp:latest
    - name: Sube sha a Docker Hub
      run: docker push islasgeci/validate_tdp:${GITHUB_SHA:0:4}
